// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface AuthenticateRequest {
  /** dummy values */
  token: string;
}

export interface User {
  id: number;
  email: string;
}

/**
 * functions defination to expose to Other Services;
 * PRETTY STRAIGHT FORWARD!!! fn -> (in) returns (out)
 * AuthService > AuthServiceClient & AuthServiceController interdaces with authenticate method
 * 🔰SEND grpc Request > AuthServiceClient.authenticate({token}) method ;
 * 🔰recieve grpc Request > AuthController.authenticate() ;
 */

export interface AuthServiceClient {
  authenticate(request: AuthenticateRequest): Observable<User>;
}

/**
 * functions defination to expose to Other Services;
 * PRETTY STRAIGHT FORWARD!!! fn -> (in) returns (out)
 * AuthService > AuthServiceClient & AuthServiceController interdaces with authenticate method
 * 🔰SEND grpc Request > AuthServiceClient.authenticate({token}) method ;
 * 🔰recieve grpc Request > AuthController.authenticate() ;
 */

export interface AuthServiceController {
  authenticate(request: AuthenticateRequest): Promise<User> | Observable<User> | User;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
