// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: proto/products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface CreateProductRequest {
  name: string;
  category: string;
  price: number;
  stock: number;
  rating: number;
  description: string;
}

export interface CreateProductResponse {
}

/**
 * ار-پی-سی فانکشن :
 * input data> from client-> grpcServer (incoming request)
 * output data> grpcServer(response)!
 * both by calling this rpc method!
 */

export interface ProductsServiceClient {
  createProduct(request: CreateProductRequest): Observable<CreateProductResponse>;
}

/**
 * ار-پی-سی فانکشن :
 * input data> from client-> grpcServer (incoming request)
 * output data> grpcServer(response)!
 * both by calling this rpc method!
 */

export interface ProductsServiceController {
  createProduct(
    request: CreateProductRequest,
  ): Promise<CreateProductResponse> | Observable<CreateProductResponse> | CreateProductResponse;
}

export function ProductsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createProduct"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_SERVICE_NAME = "ProductsService";
