name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [jobs, executor, auth]
    steps:
      # CHANGED: Checkout full repo without filter
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # NEWEST CHANGED: Verify package-lock.json in jobber/ folder
      - name: Verify package-lock.json
        run: |
          echo "Checking package-lock.json in jobber/..."
          if [ ! -f jobber/package-lock.json ]; then
            echo "Error: package-lock.json not found in jobber/!"
            exit 1
          fi
          ls -la jobber/package-lock.json

      # NEWEST CHANGED: Setup Node with correct cache path for jobber/package-lock.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: jobber/package-lock.json
          always-auth: false
          check-latest: false

      # protoc package
      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0

      # NEWEST CHANGED: npm install inside jobber folder
      - run: npm ci --legacy-peer-deps
        working-directory: jobber

      - uses: nrwl/nx-set-shas@v4

      # NEWEST CHANGED: Verify Nx workspace exists in jobber
      - name: Verify Nx workspace
        run: |
          echo "Checking Nx workspace files in jobber/..."
          if [ ! -f jobber/nx.json ]; then
            echo "Error: nx.json not found in jobber/!"
            exit 1
          fi
          ls -la jobber/nx.json

      # NEWEST CHANGED: Run nx affected inside jobber folder
      - run: npx nx affected -t lint test build
        working-directory: jobber

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # NEWEST CHANGED: Build and push Docker image with context = jobber
      - name: Build and push ${{ matrix.app }} image
        uses: docker/build-push-action@v5
        with:
          context: jobber
          file: ./apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:latest

      # NEWEST CHANGED: Nx CI fix in correct folder
      - run: npx nx fix-ci
        if: always()
        working-directory: jobber
